# Generated by Django 3.2.4 on 2021-06-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hostmain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default=None, max_length=30)),
                ('hostemail', models.EmailField(default=None, max_length=30)),
                ('pass1', models.CharField(default=None, max_length=30)),
                ('pass2', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default=None, max_length=30)),
                ('question', models.CharField(default=None, max_length=1000)),
                ('option1', models.CharField(default=None, max_length=300)),
                ('option2', models.CharField(default=None, max_length=300)),
                ('option3', models.CharField(default=None, max_length=300)),
                ('option4', models.CharField(default=None, max_length=300)),
                ('rightoption', models.CharField(default=None, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default=None, max_length=30)),
                ('username', models.CharField(default=None, max_length=30)),
                ('useremail', models.EmailField(default=None, max_length=30)),
                ('userpass1', models.CharField(default=None, max_length=30)),
                ('userpass2', models.CharField(default=None, max_length=30)),
                ('attempt', models.BooleanField(default=True)),
                ('score', models.IntegerField(default=-1)),
            ],
        ),
    ]
